GET http://localhost:3000/api/vehicles HTTP/1.1

###

GET http://localhost:3000/api/vehicle?id=16 HTTP/1.1

###

POST http://localhost:3000/api/vehicle HTTP/1.1
content-type: application/json

{
    "description": "White Toyota Quantum",
    "regNumber": "CA 234-897",
    "total_liters": "40",
    "total_amount": "1200",
    "total_distance": "443278"
}

###
POST http://localhost:3000/api/refuel HTTP/1.1
content-type: application/json

{
    "vehicleId" : 245, 
    "liters" : 30, 
    "amount" : 675, 
    "distance" :  56003, 
    "filledUp" : true
}

###
POST http://localhost:3000/api/refuel HTTP/1.1
content-type: application/json

{
    "vehicleId" : 16, 
    "liters" : 20, 
    "amount" : 500, 
    "distance" : 56500, 
    "filledUp" : true
}

###

###